

output$pageStub <- renderUI(tagList(
  #tags$head(includeHTML("google-analytics.html")),
  
  #10/1/21
  #fluidRow(column(6,
  #   DT::DTOutput('tablectries')
  #        )), #end 10/1/21
  
  fluidRow(
    #column(10,
    HTML(         "<BR><p style='margin-left:40px;margin-right: 30px'>The national COVID-19 response summaries below provide context for the graphs and data presented elsewhere on this site.</p>",
                  "<BR><p style='margin-left:40px;margin-right: 30px'>In addition, Tables 1 and 2 at the bottom of this page serve to remind that differences between countries, in terms of testing systems, strategies and deaths definitions, will impact the comparability of different countries on this website.</p>",
                  "<BR><p style='margin-left:40px;margin-right: 30px'>Therein lies one of the key learnings from our collaboration- if countries can work together to decide on standards regarding labelling of cases and deaths, comparisons of international data will contribute more to evidence about what is working (and what is not) in a given country's pandemic response.</p>",
                  "<p style='margin-left:40px;margin-right: 30px;color:#009999;font-size:16px'><BR><b>Faroe Islands</b> [p 48,700]</p>",
                  "<p style='margin-left: 40px;margin-right: 30px;color:#7575a3;font-size:11px'><b>Team:</b> Dr Pal Weihe, Dr Maria Skaalum Petersen</p>",
                  "<p style='margin-left:50px;margin-right: 30px'>The first detection of COVID-19 was on the 4th March 2020 and was associated with Faroese citizens returning from France.",
                  "<BR>A societal lockdown was introduced on March 12th while the government introduced measures to contain the spread of the COVID-19, including advice on",
                  "reducing unnecessary travel, encouraging self-quarantine of returning travelers, restricting visits to hospitals and care homes, and suggested cancellation of events with > 100 people.", 
                  "<BR>In mid-March kindergartens, schools and educational institutions closed and non-critical works were encouraged to work from home. ",
                  "The government also appealed to all restaurants, cafes, bar and nightclubs to close by 22:00 daily.",
                  "Temporary border control on entry to the Faroe Islands from abroad was introduced on the 17th of March. Lockdown was gradually lifted in early April",
                  "and the last positive test during the first wave of COVID-19 was registered on the 22nd of April.", 
                  "After 104 days without any known cases of COVID-19, on the 4th of July a returning traveller tested positive. ",
                  "The second wave of COVID-19 began in earnest on the 4th of August. The rapid resurgence in the Faroes in early Autumn is attributable to loosened ",
                  "border restrictions where, on June 15, regulations were changed from 14 days quarantine for travelers to a single negative test at the border. ",
                  "This did not immediately lead to a rise in identified cases. However, following large gatherings, e.g. private parties, and the national festival (July 28/29)",
                  ", a large outbreak of COVID-19 occurred presumably because infected individuals who had tested negative at the border had participated. ",
                  "<BR>As of 17 October 145,700 tests for COVID-19 have been completed in the Faroe Islands, with 485 confirmed cases and no fatalities. </p>",
                  "<p style='margin-left:40px;margin-right: 30px;color:#006699;font-size:16px'><b>Finland</b> [p 5,520,000]</p>",
                  "<p style='margin-left: 40px;margin-right: 30px;color:#7575a3;font-size:11px'><b>Team:</b> Prof Katri Vehvilainenjulkunen</p>",
                  "<p style='margin-left:50px;margin-right: 30px'>On 29 January 2020, the first case of COVID-19 in Finland was confirmed, when a Chinese tourist visiting Ivalo from Wuhan tested positive for the virus. ",
                  "<BR>Finland was closed down gradually in March 2020 and strict rules were applied to the whole country. Cases and deaths peaked in April, and most deaths were in older people's nursing homes at that time.  ",
                  "<BR>Finland was re-opened gradually since June 2020 and summer due to very low cases of COVID-19. ",
                  "<BR>The number of new coronavirus infections started to rise in September again and in younger age groups (students) than previously. ",
                  "<BR>By 21st October '20 2020 total death toll was 355, 65 patients are in hospital and 7 in the intensive care unit. ",
                  "The majority of the new cases have been reported in the Hospital District of Helsinki and Uusimaa and the Vaasa Hospital District. The majority of the new cases are of domestic origin. ",
                  "<BR>The epidemiological situational picture in the country is divided into three stages: basic level, acceleration stage and spreading stage. ",
                  "Local and regional epidemic prevention measures are used based on the Communicable Diseases Act, and regional prevention measures ",
                  "are considered to play a key role in dealing with the spread of infections. Koronavilkku - a contact tracing app produced by the Finnish Institute for Health and Welfare (THL) ",
                  "was launched at the end of August to help to find out whether you may have been exposed to coronavirus ('https://koronavilkku.fi/en/'). ",
                  "COVID trends from Finland are posted daily on the website of the Finnish Institute for Health and Welfare, (info in English <a href= 'https://thl.fi/en/web/thlfi-en/'>here</a>).",
                  "<BR> As of October 21st, there have been 14,250 cases of COVID-19 and 355 deaths in Finland</p>",
              "<p style='margin-left: 40px;margin-right: 30px;color:#e6103b;font-size:16px'><b>Greenland</b> [p 57,000]</p>",
              "<p style='margin-left:50px;margin-right: 30px'>On 16 March, the first case in Greenland, an autonomous territory of Denmark, was confirmed. ",
              "<BR>The first infected patient lived in the capital, Nuuk, and was placed in home isolation. ", 
              "<BR>Public gatherings of more than 100 people have been discouraged and citizens returning from high-risk areas were recommended to self-isolate for two weeks since early on in the pandemic. ",
              "On 28 March, the government prohibited the sale of alcoholic drinks until 15 April in Greenland.",
              "<BR>All non-essential flights to and from Greenland, as well as domestic flights, were strongly advised against. ",
              "While Greenland has removed visitor number restrictions as of October, there are a number of requirements for anyone wishing to enter the country, including strict testing and quarantine guidelines. ",
              "Visitors must also complete a 'Sumut' form, which details where you will be visiting and whom you will come in contact with.",
              "<BR>* Sources: https://visitgreenland.com/articles/corona-virus-status/#healthauthorities + https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Greenland",
              "<BR>In total, as of October 21st, there have been 17 confirmed cases in Greenland, with no deaths. </p>" ,
                 "<p style='margin-left: 40px;margin-right: 30px;color:#3399ff;font-size:16px'><b>Iceland</b> [p 339,000]</p>",
         "<p style='margin-left:50px;margin-right: 30px'>The first case of COVID-19 was confirmed in Iceland on February 28th. ",
         "The Icelandic Civil Protection Department declares a 'danger alert level' on the same day. <BR>The response of the Icelandic authorities and ",
         "the objectives of the COVID-19 measures taken have been clear from the outset. The focus has been on ensuring that ",
         "Iceland's essential infrastructure, particularly the healthcare system, is capable of handling the workload inevitably generated by the disease. ",
         "The main measures taken included early identification of risk areas and quarantine and/or testing of travellers arriving from these areas.",
         "<BR>From the outset there has been a strong focus on testing as many people as possible and tracing all infections to the fullest extent possible.",
         "Everybody who has had contact with infected people are ordered to quarantine.",
         "<BR> There are also restrictions on gatherings, while secondary schools and universities use distance learning. ",
         "There is limited running of nursery schools and primary schools. ",
         "<BR>Finally, there is a strong focus on continuously educating the public and providing information. Information is published on the covid.is website in 11 languages. ",
         "Regular press conferences with the Chief Epidemiologist and the Civil Protection Department are broadcast live by Iceland's major media outlets.",
         "Despite initial subsidence of the first wave of COVID-19 in Iceland in May, there has been a resurgence ,since August, as seen in other European countries.",
         "<BR>*Source: adapted from https://www.covid.is/sub-categories/icelands-response",
         "<BR>As of 21st October '20, there have been 4,260 cases of COVID and 11 COVID-19 deaths in Iceland.</p>",
       "<p style='margin-left: 40px;margin-right: 30px;color:#339966;font-size:16px'><b>Ireland</b> [p 4,904,000]</p>",
         "<p style='margin-left: 40px;margin-right: 30px;color:#7575a3;font-size:11px'><b>Team:</b> Prof Liam Glynn, Dr Mike O'Callaghan, Dana Pearl, Olivia Hickey</p>",
         "<p style='margin-left:50px;margin-right: 30px'>Ireland recorded its first confirmed case of COVID-19 on the 29th Feb 2020.",
"<BR>Adequate testing systems took some time to be established. High rates of infection in older age groups and in nursing homes/residential ",
"in March and April led to relatively high numbers of COVID-19 deaths. <BR>More recently, a more expansive and robust testing strategy and better shielding of older age groups ",
"has led to fewer deaths during this 'second wave'. <BR>However, sharp rises in COVID-19 activity in September and October are very concerning ",
"due to the likely direct and indirect pressures this will put on our health service.<BR>",
"In addition, inadequate tracing capacity to match the surge in testing and increase in identified COVID-19 cases has been a hallmark of this 'second wave'.",
"The result has been the re-introduction of a nationwide 'Level 5' (the most restrictive level) lockdown on the 21st October '20 2020.",
"<BR>COVID trends from Ireland are posted daily <a href= 'https://data.gov.ie/dataset/covidstatisticsprofilehpscirelandopendata1'>here</a>.",
"<BR>As of 21st October '20, there have been 53,400 cases of COVID and 1,868 COVID-19 deaths in the Republic of Ireland.</p>",
"<p style='margin-left: 40px;margin-right: 30px;color:#999966;font-size:16px'><b>Norway</b> [p 5,516,000]</p>",
"<p style='margin-left: 40px;margin-right: 30px;color:#7575a3;font-size:11px'><b>Team:</b> Dr Annette Fosse</p>",
"<p style='margin-left:50px;margin-right: 30px'>Norway recorded its first confirmed case of COVID-19 on the 26th February 2020. <BR>",
"On the 12th March 2020 Norway was 'closed down' by the Government. Due to lack of testing systems and equipment, vulnerable staff situation and difficult geographic and weather-related circumstances many rural communities adopted stricter local quarantine rules. <BR>",
"The initial rise in COVID-19 cases in March and April were mostly due to Norwegians coming home from ski holidays in the Alpes. <BR>",
"Most deaths were among older age groups mainly in nursing home settings.",
"Norway was gradually re-opened during May and June.", 
"<BR>Work on the epidemic is following two paths: an infection control strategy to reduce transmission and a treatment strategy to prevent deaths among people who become severely ill. ", 
"The infection control strategy aims to delay the onset of the epidemic and give the healthcare service more time to prepare, and then slow down transmission so that the epidemic is spread over a longer period and fewer become infected overall. ",
"<BR>COVID trends from Norway are posted daily <a href= 'https://www.fhi.no/en/id/infectious-diseases/coronavirus/'>here</a>.",
"<BR>By the 21th October cases confirmed stands at 17,125, while total death toll in Norway is modest: 279.<BR></p>",
"<p style='margin-left: 40px;margin-right: 30px;color:#9900cc;font-size:16px'><b>Northern Ireland</b> [p 1,822,000]</p>",
         "<p style='margin-left:50px;margin-right: 30px'>Northern Ireland confirmed its first case of COVID-19 in late February 2020. In keeping with the rest of the United Kingdom, Northern Ireland responded to the COVID-19 pandemic by implementing a series of strict measures to slow the spread of the virus, including lockdowns, travel restrictions, and the closure of non-essential businesses. The government also launched a robust testing and tracing system to identify and isolate positive cases. For a COVID-19 death to be recorded as such in Northern Ireland, the patient required a positive test for COVID-19 in the 28 days prior to their death.",
         "<BR>As of 21st October '20, there have been 31,034 cases of COVID and 629 COVID-19 deaths in Northern Ireland.</p>",
         "<p style='margin-left: 40px;margin-right: 30px;color:#3333cc;font-size:16px'><b>Scotland</b> [p 5,454,000]</p>",
         "<p style='margin-left:50px;margin-right: 30px'>The first case of COVID-19 was detected in Scotland in early March 2020. By mid-March, the Scottish Government advised the public to avoid all 'non-essential' travel and contact with others, and to work from home where possible. Those with symptoms, and their household, were asked to self-isolate. Pregnant women, the over 70s, and those with significant illnesses were asked to self-isolate for longer. On 20th March 2020, schools were closed, in addition to pubs, cafes and cinemas. On 23rd March 2020, a 'Stay at Home' order was announced. For a death to be considered a COVID-19 death in Scotland, similar to Northern Ireland, the patient required a positive test for COVID-19 in the 28 days prior to their death.",
         "<BR>As of 21st October '20, there have been 50,903 cases of COVID and 2,653 COVID-19 deaths in Scotland.</p>",
         "<p style='margin-left: 40px;margin-right: 30px;color:#ffa31a;font-size:16px'><b>Sweden</b> [p 10,230,000]</p>",
         "<p style='margin-left:50px;margin-right: 30px'>SARS-CoV-2 was confirmed to have reached Sweden on 31st of January 2020, when a woman returning from Wuhan tested positive. ",
"On 26th of February, multiple travel-related clusters appeared in Sweden.", 
"Community transmission was confirmed on the 9th of March in the Stockholm region. ",
"<BR>Sweden has attracted attention internationally for having less stringent restrictions than neighbouring countries.",
"There is no general requirement to wear a face mask in normal social situations, in public places, in public transport etc., as the the Public Health Agency of Sweden ('Folkhalsomyndigheten') await stronger evidence of their benefit.",
"Public gatherings and events may have a maximum of 50 participants and the police can cancel or disband a public gathering or event with more than 50 participants. ",
"However, restaurants and cafes are exempted from the 50-person limit. ",
"<BR> Primary schools did not close early on in the pandemic, and have reopened as normal after the usual summer break.",
"<BR>People have been advised to work from home where possible and people aged 70 or more are advised to stay at home as much as possible.",
"<BR>There has been an entry ban for visitors from outside the EU in force since mid-March, and this is to remain in place until the end of October.",
"<BR>For Swedish citizens and visitors from the EU, it is recommended that those who are feeling unwell should stay at home, people should stay at least an arm's length away from other people in public and that everyone should wash their hands frequently with soap and water.",
"Access to PCR testing for people in Sweden can be organised by calling 1177. ",
"<BR>*Sources: www.krisinformation.se/en/ + www.folkhalsomyndigheten.se + https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Sweden",
"<BR>As of October 21st, there have been 108,900 cases of COVID-19 confirmed in Sweden, with 5,900 deaths.</p><BR><BR>",
"<BR><p align='center'><b>Table 1:</b> Testing Strategies by Country</p>",
"<p align='center'><img src='testingstrategies.png', width='90%', height='90%''></p>",
"<BR><BR><p align='center'><b>Table 2:</b> Deaths Definitions by Country</p>",
"<p align='center'><img src='deathsdefinitions.png', width='80%', height='80%''></p>")
  )
))


#output$tablectries <- renderTable({
output$tablectries <- DT::renderDT({
  summarylines
})
